wlan: qcacld-3.0: Enable WLAN_OBJMGR_DEBUG for blair gki target
Fix a modpost link failure when building qcacld-3.0 with the
gki variant:
  ERROR: modpost: "wlan_objmgr_trace_init_lock" [wlan.ko] undefined!
  ERROR: modpost: "wlan_objmgr_trace_ref" [wlan.ko] undefined!
  ERROR: modpost: "wlan_objmgr_trace_deinit_lock" [wlan.ko] undefined!
  ERROR: modpost: "wlan_objmgr_trace_del_ref_list" [wlan.ko] undefined!
  Failed to build Target //vendor/qcom/opensource/wlan/qcacld-3.0:blair_gki_wlan_modules_dist
[blair_gki_wlan_defconfig](cci:7://file://vendor/qcom/opensource/wlan/qcacld-3.0/configs/blair_gki_wlan_defconfig:0:0-0:0) sets `CONFIG_WLAN_OBJMGR_REF_ID_TRACE=y`.

This configuration enables the declaration and invocation of the
`wlan_objmgr_trace_*` functions throughout the object manager code
(vdev, peer, pdev)
The implementation of the trace functions resides in `wlan_objmgr_debug.c`,
which is only compiled into the module when `CONFIG_WLAN_OBJMGR_DEBUG` is
enabled. Without it, the build fails at the modpost stage due to
unresolved external symbols